server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9090/eureka
  instance:
    preferIpAddress: true

kafka:
  bootstrapServer: kafka-headless:9092
  topics:
    product: product

spring:
  application:
    name: xotomicro-back-product-service
  redis:
    host: product-redis-master
    port: 6379
    database: 0
    timeout: 60000
    default-ttl-in-mins: 5
  datasource:
    url: jdbc:postgresql://product-db-postgresql:5432/boilerplate
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  user: postgres
  password: admin
  url: jdbc:postgresql://product-db-postgresql:5432/boilerplate
